# Generated by Django 5.2.7 on 2025-10-29 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='header',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_id', message='ID de playlist inválido.', regex='^[A-Za-z0-9]+$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='spotify_playlist_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
