# Generated by Django 5.2.7 on 2025-10-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_header_profile_playlist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header',
            field=models.ImageField(blank=True, max_length=120, upload_to=''),
        ),
    ]
