# Generated by Django 5.2.7 on 2025-10-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='headers/'),
        ),
    ]
