# Generated by Django 5.2.7 on 2025-10-29 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_user_instruments_alter_room_creator_and_more'),
        ('users', '0003_alter_profile_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='access_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='room',
            name='privacy',
            field=models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], max_length=20),
        ),
    ]
