# Generated by Django 5.2.7 on 2025-11-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_access_code_alter_room_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='access_code',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
    ]
